---
title: "Short CV"
author: "JJ Merelo, `jmerelo@ugr.es`, [Google Scholar Profile](https://scholar.google.com/citations?hl=es&user=gFxqc64AAAAJ)"
date: "`r Sys.Date()`"
output: word_document
abstract: |
  JJ Merelo is a professor at the University of Granada, currently attached to the
  Computer Engineering, Automatics and Robotics department. He graduated in
  Physics at the same university in 1988, obtaining a PhD in Physics in 1994,
  again from the same university.
bibliography: bibliography.bib
---

```{r setup,echo=FALSE,message=FALSE}
require(scholar)
myId <- 'gFxqc64AAAAJ'
myProfile <- get_profile(myId)
myPapers <- get_publications(myId)
```


## Teaching

JJ Merelo started teaching in 1988, and has been teaching ever since, mainly in Computer Science degrees, also in Telecommunications and other degrees, continuing education courses, as well as industry courses. He taught a course on MLOps at NOVA university in Lisbon in summer 2022, his last outside normal university degrees.

He has participated as keynote speaker in JENUI, the Spanish conference for Computer Science professors. He has also participated in internal formation courses, mainly related to new technologies applied to teaching, open source software and open culture.

His teaching innovation activities include using free software for teaching, as well as the application of chatbots and learning analytics to teaching [@guervos2004weblogging,@chatbots].

He is currently teaching a Cloud Computing class in the Computer Science degree, and using very extensively GitHub to deliver value to students and enhance their programming skills.

## Research

His main interests are evolutionary algorithms, neural networks (the topic of his PhD), complex networks (including social networks), digital humanities and parallel, ephemeral and social computing, always from the perspective of open science. Since 2005, most of his papers are written openly using GitHub, where data and code used to process it and generate tables and graphics can also be downloaded and reused with a free license.

Currently, his Google Scholar profile includes `r length(myPapers$title)` papers, with a total of `r myProfile$total_cites` citations, and an `h` number of `r myProfile$h_index`.

Papers are developed openly in a GitHub repository, with a free license. Some highlights on different topics include:

* [@histories3010003], a digital humanities paper, with data and code available from [its GitHub repository](https://github.com/JJ/dogesr). It uses data included in the open source R package [`dogesr`](https://cloud.r-project.org/web/packages/dogesr/index.html).
* [@garcíaortega2021tropes], which analyzes the TvTropes.org website looking for patterns in movie tropes, is also listed in [PapersWithCode](https://cs.paperswithcode.com/paper/tropes-in-films-an-initial-analysis-1), pointing to the repository where it was developed and where data is hosted.
* Data on his complex network analysis in soccer [@futbol] was released in [ResearchGate](https://www.researchgate.net/publication/51928441_FIFA_World_Cup_2010_A_Network_Analysis_of_the_Champion_Team_Play) and can be used directly.
* His paper that established the state of the art in the game of Mastermind [@mastermind] included also the publication of several Perl libraries to CPAN, as well as the code and all the data used and generated by the experiments.

In general, we are committed to open science and see it as a philosophy that gets science closer to society, at the same time it improves discovery by any scientist or amateur of scientific results.

## Science administration

In 2008 he was appointed as director of the (previously inexistent) University Open Source Program Office (OSL, Oficina de Software Libre). He held the job until 2017, pushing for adoption of open science, open source software, and open culture in the university of Granada. 

## Other professional activities

He has published several technical books under Apress (a Springer imprint) [@mereloraku,@mereloperl6]. He has been also under contract with polypoly senior software engineer since May 2021 to November 2022.

## Programming

JJ's experience in programming goes back to 1983; he has not stopped being an
active software developer since then. He is mainly proficient in Perl, Raku and
JavaScript in any of its forms. Can use effectively R and Python, as well as
other languages like Go.

## References
