name: "Generate CV"

on:
  push:
    path: cv.tex

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tools
        run: .github/workflows/latex-install.sh
      - name: Generate pdf
        run: ./generate_cv.sh
      - name: Generate thumbnail
        run: thumbpdf --makepng --verbose --noclean cv.pdf && && mv thb1.png cv.png
      - name: Pushes Thumbnail
        env:
          USER_NAME: JJCVBot
          EMAIL: jjmerelo@gmail.com
          MY_COMMIT_MSG: Updates thumbnail
        run: curl https://raw.githubusercontent.com/JJ/perl-GitHub-Actions/main/bin/commit-push.pl | perl
      - name: Publishes cv
        uses: actions/upload-artifact@v2
        with:
          name: Fresh CV
          path: cv.pdf
