name: "Generate CV"

on: [ push ]

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installs tools
        run:
          sudo apt-get install texlive-xetex biber fonts-goudybookletter texlive-fonts-extra texlive-math-extra fonts-adf-accanthis fonts-smc-gayathri
      - name: Generate pdf
        run: ./generate_cv.sh
