name: "Generate CV"

on:
  push:
    path: cv.tex

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate URL
        run: .github/workflows/generate-download-url.pl

