name: "Generate academic CV"

on:
  push:
    paths:
      - '*.Rmd'
      - .github/workflows/generate-cv.yml
  schedule:
    - cron:  '1 1 1,15 * *'

jobs:
  generate-academic-cv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: Install latex
        run: sudo apt-get install -y texlive-latex-recommended
      - name: Generate summary file
        run: bin/rmd-render.R academic-cv-summary.Rmd

      - uses: actions/upload-artifact@v4
        with:
          name: academic-cv
          path: text/academic-cv-summary.pdf
