name: "Generate CV"

on:
  push:
    path: cv.tex

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: latex
        with:
          path: ${{ runner.temp }}/latex
          key: ${{ runner.os }}-cache-latex
      - uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: './latex-install.sh'
          is_cached: ${{ steps.latex.outputs.cache-hit }}
          cache: ${{ runner.temp }}/latex
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'
      - name: Generate pdf
        run: ./generate_cv.sh
      - name: Generate thumbnail
        run: thumbpdf cv.pdf && mv cv-0.png cv.png
      - name: Pushes Thumbnail
        env:
          USER_NAME: JJCVBot
          EMAIL: jjmerelo@gmail.com
          MY_COMMIT_MSG: Updates thumbnail
        run: curl https://raw.githubusercontent.com/JJ/perl-GitHub-Actions/main/bin/commit-push.pl | perl
      - name: Publishes cv
        uses: actions/upload-artifact@v2
        with:
          name: Fresh CV
          path: cv.pdf
