name: "Generate CV"

on:
  push:
    path: cv.tex

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installs tools
        run:
          sudo apt-get install texlive-xetex biber fonts-goudybookletter texlive-fonts-extra  texlive-science-doc texlive-science fonts-adf-accanthis fonts-smc-gayathri
      - name: Generate pdf
        run: ./generate_cv.sh
      - name: Publishes cv
        uses: actions/upload-artifact@v2
        with:
          name: Fresh CV
          path: cv.pdf
